### ISSUE TITLE
Infinite loop in vwarn / vwarnc with netcat

### ISSUE THREAD

**Issue by Thannoy** [sickill/stderred#26]
Netcat does write an error when I press [enter] in a unidirectional UDP socket,
but netcat crash when doing the same when atderred is activated.

When stderred is disabled everything works as expected
--------------------------------------------------------------------------------

 > 0)-d1-!1065:~/bin/stderred$ LD_PRELOAD= nc -u -l  1201
 [��$]
 nc: Write error: Connection refused

I get an uncolored error and nc continue to listen.

When I enable stderred (up to date 11e4a33af), and for the same command:
-------------------------------------------------------------------------------------------------------------

> GNU gdb (GDB) Fedora (7.3.1-46.fc15)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/nc...(no debugging symbols found)...done.
Missing separate debuginfos, use: debuginfo-install nc-1.100-3.fc15.i686
(gdb) r
Starting program: /usr/bin/nc -l -u 1201
[��$]
> 
> Program received signal SIGSEGV, Segmentation fault.
0x41b03fac in vwarnc () from /usr/lib/libbsd.so.0
(gdb) 

Backtrace shows an infinite loop in three functions:
> (gdb) bt 5
#0  0x41b03fac in vwarnc () from /usr/lib/libbsd.so.0
#1  0x00112b7b in vwarnc () from //home/actech/bin/libstderred.so
#2  0x00112e2b in vwarn () from //home/actech/bin/libstderred.so
#3  0x41b03fde in vwarnc () from /usr/lib/libbsd.so.0
#4  0x00112b7b in vwarnc () from //home/actech/bin/libstderred.so
(More stack frames follow...)
(gdb) bt -5
#153515 0x00112e2b in vwarn () from //home/actech/bin/libstderred.so
#153516 0x41b03fde in vwarnc () from /usr/lib/libbsd.so.0
#153517 0x00112b7b in vwarnc () from //home/actech/bin/libstderred.so
#153518 0x00112e2b in vwarn () from //home/actech/bin/libstderred.so
#153519 0x41b03fde in vwarnc () from /usr/lib/libbsd.so.0

I added '-g' in CFLAGS (in top-level Makefile) with no luch to get crash details.

Here are some details about my nc binary if it can help:
> $ file /usr/bin/nc
     /usr/bin/nc: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, stripped
$ ldd /usr/bin/nc
	linux-gate.so.1 =>  (0x00429000)
	//home/user/bin/libstderred.so (0x00b4e000)
	libbsd.so.0 => /usr/lib/libbsd.so.0 (0x41b02000)
	libc.so.6 => /lib/libc.so.6 (0x41974000)
	libdl.so.2 => /lib/libdl.so.2 (0x41b1e000)
	/lib/ld-linux.so.2 (0x41953000)

stderred works very fine in other cases.
Great work! Thanks!

**Comment by sickill** [comment]
:+1:
