### ISSUE TITLE
macos: stderred breaks interactive prompts due to line buffering

### ISSUE THREAD

**Issue by ssbarnea** [sickill/stderred#60]
I found at few cases where `stderred` produces a serious issue: the script running stopped and and I didn't know what happened until I stopped it (or gave some input).

Here is the a reproducing bug:
```
>&2 unbuffer echo -n "Are you sure you want to nuke everything?! "
read -n 1 yn
```

This is a real deal because the user has no idea what's happening until is too late. Imagine what could happen.... I was lucky that I didn't press the wrong keys.

**Comment by ssbarnea** [comment]
Somehow it seems that this problem becomes worse and worse after upgrading to High Sierra encountering more and more cases where a command is stuck with no visible reason on screen.

Any ideas on how to avoid this? I think I encountered on almost any tool that does prompt the user (interactive).

Example: Try to run "pip install tendo; pip uninstall tendo" -- the package has nothing to do with it, it will replicate with any package and is not pip fault. I go the same error with `git`.

**Comment by sickill** [comment]
Not really sure. To be honest, I haven't looked at this project in a while, and @cehoffman was doing most of the latest development work here.

**Comment by ssbarnea** [comment]
@cehoffman @sickill I really love this feature of coloring stderr as it improves the terminal UX considerably. Still, this bug which affects most tools that do interactive prompts, like yn is almost a blocker, as you endup with the terminal stuck without reason, that's because the "prompt" is not displayed, it is displayed only after you press enter.

As you can imagine, this is also dangereus as the prompt could be "press ENTER to obliterate the world!".

Any ideas on how to fix it or to workaround it, without loosing stderred?

**Comment by cehoffman** [comment]
I haven't been able to experience this this issue. My daily driver is a mac. The way stderred does coloring was to chosen explicitly to combat buffering since the color codes are inserted in line in the same stream and buffer the program would normally use. You can try adding a step in https://github.com/sickill/stderred/blob/master/src/stderred.c#L39 to call [setbuf](http://man7.org/linux/man-pages/man3/setbuf.3.html) with the stderr FILE and NULL as the second arg, e.g. `setbuf(stderr, NULL)`. This shouldn't be necessary though because stderr is unbuffered by default.

**Comment by ssbarnea** [comment]
I am not sure what is causing the issue bug here is the proof:
```
ssbarnea@smac: ~/os/jira master ⚡ $ pip uninstall tendo                                                                                            [15:48:21]
Uninstalling tendo-0.2.12:
  Would remove:
    /Users/ssbarnea/.pyenv/versions/2.7.14/lib/python2.7/site-packages/tendo.egg-link
^CProceed (y/n)? Operation cancelled by user
FAIL: 1
```
As you can see the text is printed after I pressed the Ctr-C. Maybe this has something to do with the fact that I am using zsh as my shell instead of bash.

**Comment by ssbarnea** [comment]
It is bit fun because while trying to test your workaround I discovered that I was not really loading the library. My shell contained the snippet from https://github.com/cehoffman/dotfiles/blob/master/zsh/config#L167 which was supposed to load ~/.homebrew/lib/libstderred.dylib but that file did not exist and even after building and changing the code so it will point to the freshly build library it would not do anything. 

Looking at the logic of the code I realise that what I was really using was the "colorize" shell function. I a not even sure when stderrerr stopped working or if only had the impression that it was loaded.

**Comment by BatmanAoD** [comment]
Does that mean this issue can be closed?

**Comment by cehoffman** [comment]
I believe so.
