### ISSUE TITLE
"command not found" is not colored in ArchLinux

### ISSUE THREAD

**Issue by phil294** [sickill/stderred#64]
If I remember correctly from my previous Ubuntu, it should be. In x86_64 Linux 4.18.8-arch1-1-ARCH however, it's plain white.

Other commands like `cat nonexistentfile` are colored properly.

**Comment by daenney** [comment]
Command not found is usually printed by the shell itself, and not on stderr, but stdout. This would mean stderred wouldn't colorize it. `cat`ing a non-existant file is a different action altogether, cat is told the file doesn't exist by the OS and decided to print that on stderr, so it shows up in red.

However in the case of Ubuntu most shells are set up with a `command_not_found_handle`, executing a third-party program, https://launchpad.net/command-not-found, to inform you the command is not found and print possible suggestions. That one prints to stderr afaik so it would turn red.

**Comment by phil294** [comment]
Thank you - makes perfect sense!
